version: "3.3"
services:

  db:
    restart: always
    image: postgres:15.2
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      # - ./new_database.sql:/docker-entrypoint-initdb.d/new_database.sql
    # network_mode: 'host'
    ports:
      - ${PORT}:5432
